{
  "frequency": 300,
  "metricPort": 8888,
  "info": [
    {
      "network": "evm",
      "endpoints": [
          "https://andromeda.metis.io/?owner=1088",
          "https://metis-mainnet.public.blastapi.io"
      ],
      "addressList": [
        {
          "address":"0x282976F47d7C1cE8B9f956241105d5741f203fA6",
          "label":"metis_user1_account",
          "infoThreshold": 0.05,
          "warnThreshold": 0.02
        },
        {
          "address":"0x81251B395506b4BfF35DB657751285c138BFB3F5",
          "label":"metis_user2_account",
          "infoThreshold": 0.1,
          "warnThreshold": 0.02
        }
      ]
    },
    {
      "network": "starknet",
      "endpoints": [
          "https://starknet-mainnet.public.blastapi.io",
          "https://free-rpc.nethermind.io/mainnet-juno"
      ],
      "addressList": [
        {
          "address":"0x07892c7bf9fc9b9135ab18ddfdc3640d75aa56ed9761fa43bf7eda8bfdfc5919",
          "label":"starknet_user1_account",
          "infoThreshold": 0.002,
          "warnThreshold": 0.001
        }
      ]
    },
    {
      "network": "starknet_strk",
      "endpoints": [
          "https://starknet-mainnet.public.blastapi.io",
          "https://free-rpc.nethermind.io/mainnet-juno"
      ],
      "addressList": [
        {
          "address":"0x07892c7bf9fc9b9135ab18ddfdc3640d75aa56ed9761fa43bf7eda8bfdfc5919",
          "label":"starknet_strk_user1_account",
          "infoThreshold": 0.002,
          "warnThreshold": 0.001
        }
      ]
    }
  ]
}